### ISSUE TITLE
Exception: The client ZeroMQ remote API version does not match CoppeliaSim's version

### ISSUE THREAD

**Issue by gatsz1** [CoppeliaRobotics/zmqRemoteApi#13]
Here is the error message
Traceback (most recent call last):
  File "C:\Users\Ian\Desktop\project2_starter_code\exec_environment.py", line 133, in <module>
    main()
  File "C:\Users\Ian\Desktop\project2_starter_code\exec_environment.py", line 122, in main
    env = Simulation()
  File "C:\Users\Ian\Desktop\project2_starter_code\exec_environment.py", line 22, in __init__
    self.initializeSim()
  File "C:\Users\Ian\Desktop\project2_starter_code\exec_environment.py", line 26, in initializeSim    self.client.setStepping(True)   
  File "C:\Users\Ian\Desktop\project2_starter_code\zmqRemoteApi\__init__.py", line 103, in setStepping
    return self.call('setStepping', [enable,self.uuid])
  File "C:\Users\Ian\Desktop\project2_starter_code\zmqRemoteApi\__init__.py", line 71, in call
    return self._process_response(self._recv())
  File "C:\Users\Ian\Desktop\project2_starter_code\zmqRemoteApi\__init__.py", line 61, in _process_response
    raise Exception(resp.get('error'))

**Comment by gatsz1** [comment]
FIXED: 
Cloned the src code and used the python file client directly.
